### ISSUE TITLE
El cierre de documentos debe realizarse en bloques finally para evitar memory leaks.

### ISSUE THREAD

**Issue by drmillan** [SamuelFuentes/addBlankPageToPDF#1]
https://github.com/SamuelFuentes/addBlankPageToPDF/blob/33129d911eb692769d9caf15151ab760625f6d3b/src/main/java/addBlankPageToPDF.java#L47

doc:
https://stackoverflow.com/questions/4968491/java-close-pdf-error

**Comment by SamuelFuentes** [comment]
Si, al no ejecutarlo en un bloque finally, si se produjese un error, el documento se mantendría abierto y mantendría el consumo en memoria.
Para solucionarlo se ha añadido el cierre del documento en el bloque finally y se ha contemplado además, la posibilidad de un error al cerrar el documento:
```
    private static void addBlankPage(File file) {
        PDDocument document = null;
        try {
            document = PDDocument.load(file);
            PDPage blankPage = new PDPage();
            document.addPage(blankPage);
            document.save(file);
        } catch (IOException e) {
            System.out.println("Error al agregar una página en blanco al archivo " + file.getName());
        } finally {
            try {
                document.close();
            } catch (IOException e) {
                System.out.println("Error al cerrar el documento " + file.getName());
            }
        }
    }
```
