### ISSUE TITLE
Las clases java deben definirse dentro de un paquete, y su nombre debe iniciar con Mayúsculas

### ISSUE THREAD

**Issue by drmillan** [SamuelFuentes/addBlankPageToPDF#2]
https://github.com/SamuelFuentes/addBlankPageToPDF/blob/33129d911eb692769d9caf15151ab760625f6d3b/src/main/java/addBlankPageToPDF.java#L7

doc:
https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

**Comment by SamuelFuentes** [comment]
Si, ha sido un gran despiste.
` public class AddBlankPageToPDF { `
